import { z } from "zod/v4";

// Wise currency enum and helpers
export const WISE_CURRENCIES = [
  "AED","AUD","BGN","BRL","CAD","CHF","CLP","CZK","DKK","EUR","GBP",
  "HKD","HRK","HUF","IDR","ILS","INR","JPY","KRW","MXN","MYR","NOK",
  "NZD","PHP","PLN","RON","SEK","SGD","THB","TRY","USD","ZAR",
] as const;

export const currencyEnum = z.enum(WISE_CURRENCIES);

// Export types for business categories if needed later
export const WISE_BUSINESS_CATEGORIES = {
  CHARITY: ["CHARITY_NON_PROFIT", "CHARITY_ALL_ACTIVITIES"],
  CONSULTING_AND_SERVICES: [
    "CONSULTING_IT_BUSINESS_SERVICES",
    "ADVERTISING_AND_MARKETING",
    "ARCHITECTURE",
    "COMPANY_ESTABLISHMENT_FORMATION_SERVICES",
    "DESIGN",
    "FINANCIAL_CONSULTING_ACCOUNTING_TAXATION_AUDITING",
    "IT_DEVELOPMENT",
    "IT_HOSTING_SERVICES",
    "IT_CONSULTING_AND_SERVICES",
    "LEGAL_SERVICES",
    "MANAGEMENT_CONSULTING",
    "SCIENTIFIC_AND_TECHNICAL_CONSULTING",
    "SOFTWARE_AS_A_SERVICE",
    "TRANSLATION_AND_LANGUAGE_SERVICES",
    "CONSULTING_OTHER",
    "SERVICES_OTHER",
    "FREELANCE_PLATFORMS",
    "RECRUITMENT_SERVICES",
    "MAINTENANCE_SERVICES",
  ],
  MEDIA_AND_ENTERTAINMENT: [
    "DESIGN_MARKETING_COMMUNICATIONS",
    "AUDIO_AND_VIDEO",
    "PHOTOGRAPHY",
    "PRINT_AND_ONLINE_MEDIA",
    "TELECOMMUNICATIONS_SERVICES",
    "MEDIA_COMMUNICATION_ENTERTAINMENT",
    "ADULT_CONTENT",
    "FINE_ARTS",
    "ARTS_OTHER",
    "EVENTS_AND_ENTERTAINMENT",
    "GAMBLING_BETTING_AND_ONLINE_GAMING",
    "NEWSPAPERS_MAGAZINES_AND_BOOKS",
    "PERFORMING_ARTS",
    "VIDEO_GAMING",
  ],
  EDUCATION: [
    "EDUCATION_LEARNING",
    "SCHOOLS_AND_UNIVERSITIES",
    "TEACHING_AND_TUTORING",
    "ONLINE_LEARNING",
  ],
  FINANCIAL_SERVICES: [
    "FINANCIAL_SERVICES_PRODUCTS_HOLDING_COMPANIES",
    "CROWDFUNDING",
    "CRYPTOCURRENCY_FINANCIAL_SERVICES",
    "HOLDING_COMPANIES",
    "INSURANCE",
    "INVESTMENTS",
    "MONEY_SERVICE_BUSINESSES",
    "FINANCIAL_SERVICES_OTHER",
  ],
  FOOD_AND_BEVERAGES: [
    "FOOD_BEVERAGES_TOBACCO",
    "ALCOHOL",
    "FOOD_MANUFACTURING_RETAIL",
    "RESTAURANTS_AND_CATERING",
    "SOFT_DRINKS",
    "TOBACCO",
    "VITAMINS_AND_DIETARY_SUPPLEMENTS",
  ],
  HEALTH_AND_MEDICAL: [
    "HEALTH_PHARMACEUTICALS_PERSONAL_CARE",
    "HEALTH_AND_BEAUTY_PRODUCTS_AND_SERVICES",
    "DENTAL_SERVICES",
    "DOCTORS_AND_MEDICAL_SERVICES",
    "ELDERLY_OR_OTHER_CARE_HOME",
    "FITNESS_SPORTS_SERVICES",
    "MEDICAL_EQUIPMENT",
    "NURSING_AND_OTHER_CARE_SERVICES",
    "PHARMACEUTICALS",
    "PHARMACY",
  ],
  PUBLIC_SERVICES: [
    "PUBLIC_GOVERNMENT_SERVICES",
    "PUBLIC_ALL_SERVICES",
    "GOVERNMENT_SERVICES",
    "UTILITY_SERVICES",
  ],
  REAL_ESTATE: [
    "REAL_ESTATE_CONSTRUCTION",
    "REAL_ESTATE_DEVELOPMENT",
    "REAL_ESTATE_SALE_PURCHASE_AND_MANAGEMENT",
  ],
  RETAIL_AND_MANUFACTURING: [
    "RETAIL_WHOLESALE_MANUFACTURING",
    "AGRICULTURE_SEEDS_PLANTS",
    "AUTOMOTIVE_SALES_SPARE_PARTS_TRADE",
    "AUTOMOTIVE_MANUFACTURING",
    "CHEMICALS",
    "CLOTHING",
    "ELECTRICAL_PRODUCTS",
    "FIREARMS_WEAPONS_AND_MILITARY_GOODS_SERVICES",
    "HOME_ACCESSORIES_FURNITURE",
    "FINE_JEWELLERY_WATCHES",
    "FASHION_JEWELLERY",
    "LEGAL_HIGHS_AND_RELATED_ACCESSORIES",
    "MACHINERY",
    "PETS",
    "PRECIOUS_STONES_DIAMONDS_AND_METALS",
    "SPORTING_EQUIPMENT",
    "MANUFACTURING_OTHER",
    "RETAIL_WHOLESALE_MARKETPLACE_AUCTION",
    "RETAIL_WHOLESALE_OTHER",
    "TOYS_AND_GAMES",
  ],
  TRAVEL_AND_TRANSPORT: [
    "TRAVEL_TRANSPORT_TOUR_AGENCIES",
    "ACCOMMODATION_HOTELS",
    "PASSENGER_TRANSPORT",
    "FREIGHT_TRANSPORT",
    "RIDESHARING_TRANSPORT_SHARING_SERVICES",
    "TRANSPORT",
    "TRAVEL_AGENCIES",
    "TOUR_OPERATORS",
    "TRAVEL_OR_TOUR_ACTIVITIES_OTHER",
  ],
  OTHER: ["OTHER", "OTHER_NOT_LISTED_ABOVE"],
} as const;

export type FirstLevelCategory = keyof typeof WISE_BUSINESS_CATEGORIES;
export type SecondLevelCategory =
  (typeof WISE_BUSINESS_CATEGORIES)[FirstLevelCategory][number];

export const firstLevelCategoryEnum = z.enum(
  Object.keys(WISE_BUSINESS_CATEGORIES) as [string, ...string[]],
);

export const getSecondLevelCategories = (firstLevel: FirstLevelCategory): string[] =>
  firstLevel in WISE_BUSINESS_CATEGORIES
    ? [...(WISE_BUSINESS_CATEGORIES[firstLevel] as readonly string[])]
    : [];

export * from "./wise/dynamicRecipientSchema";

